name: Pull Request Test

on: [pull_request]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
  
      - name: Build
        shell: bash
        run: |
          CI/build.sh

  test_on_mac:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: 
        
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest-stable
  
      - name: Build
        shell: bash
        run: |
          CI/build.sh

